// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

/** Client is emitted next to the schema: `infrastructure/generated/prisma/` (`client.ts`, `browser.ts`, …). Run from repo root: `bun run prisma:generate`. */
export default defineConfig({
  schema: 'infrastructure/prisma/schema.prisma',
  migrations: {
    path: 'infrastructure/prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
